CREATE TABLE IF NOT EXISTS books (
  id SERIAL PRIMARY KEY,
  author VARCHAR(255),
  title VARCHAR(255),
  isbn VARCHAR(255),
  image_url VARCHAR(255),
  description TEXT
);

{
  'title': 'Battlefield Earth',
  'author': 'L. Ron Hubbard'
  'isbn': '9781592120079'
  'image_url': 'http://books.google.com/books/content?id=KF2hckiYTocC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api'
  'description': 'Jonnie Goodboy Tyler ventures out of the tiny community of humans barely surviving in the Rocky Mountain refuge and finds himself challenging the Psychlos, the malignant and oppressive alien conquerors of Earth.'
}

INSERT INTO books (author, title, isbn, image_url, description) VALUES('L. Ron Hubbard', 'Battlefield Earth', '9781592120079', 'http://books.google.com/books/content?id=KF2hckiYTocC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'Jonnie Goodboy Tyler ventures out of the tiny community of humans barely surviving in the Rocky Mountain refuge and finds himself challenging the Psychlos, the malignant and oppressive alien conquerors of Earth.');

INSERT INTO books (author, title, isbn, image_url, description) VALUES('David Brody', 'The faith of Donald J. Trump', '9780062749598', 'http://books.google.com/books/content?id=atrWDgAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'description": "Based on extensive inside sources, including exclusive interviews with the President and Vice President, The Faith of Donald J. Trump explores his rarely discussed, but deeply important, religious beliefs and relationships with leading Evangelicals. The Chief Political Correspondent for the Christian Broadcasting Network and the \"Jesus in the Public Square\" columnist for the Washington Times explore the rarely discussed, but deeply important, religious beliefs and worldview of Donald J. Trump and his advisors. Donald J. Trump was raised as a Presbyterian and has praised both Christianity and the primacy of the Bible. In the Oval Office, he has surrounded himself with close advisors who share his deep faith. In this deeply reported book, David Brody and Scott Lamb draw on unparalleled access to the White House to explain President Trump’s connection to the Christian faith, the evangelical right, the prosperity gospel, and the pressing moral and ethical issues of our day. In part, the authors argue, President Trump won over evangelicals not by pandering to them, but by supporting them and all their most important issues without pretending to be something he’s not. Though the forty-fifth president is far from the perfect vessel—he has been married three times—his supporters argue that Donald Trump may be just what America needs. This book reveals how he has surrounded himself with believers who think he is the one guiding figure who can return us to the traditional values—hard work, discipline, duty, respect, and faith—that have long been the foundation of American life, and truly make America great again in all ways.');

INSERT INTO books (author, title, isbn, image_url, description) VALUES('Jeffrey Dubinsky', 'Goldie`s Lox and the Three Bagels', '9780806528618', 'http://books.google.com/books/content?id=-Ht9eGc2-b8C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'A fun and witty new look at all the classic stories readers have grown to love, re-interpreted with Jewish soul. Featuring: Goldie`s Lox and the Three Bagels; Rumpleforeskin; Snow Whitefish and the Seven Dwarfkins; The Three Little Chazzers; Jake and Mr Bienstock; The Ugly Schmuckling and more!');

INSERT INTO books (author, title, isbn, image_url, description) VALUES('Valve CORPORATION', 'Dota 2 the Comic Collection', '9781506703480', 'http://books.google.com/books/content?id=NXcqDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'DEFENSE OF THE ANCIENTS is a highly popular Multiplayer online battle arena video game currently developed by Valve Corporation who have achieved considerable successes in the video game industry with the Half-Life and Portal franchises. Based on the Warcraft III engine, the original game was a huge favourite at gaming conventions and received considerable acclaim. After the property was acquired by Valve a standalone sequel DOTA 2 was produced and was also a huge hit and for a time was the video game with the highest of users in Steam history. Now alongside Dark Horse Valve have produced a new collection of tie-in comics that expand on the DOTA world.');

INSERT INTO books (author, title, isbn, image_url, description) VALUES('John Young', 'Super Trooper', '9781477220504', 'http://books.google.com/books/content?id=Ii-8zlWNQxwC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'description": The Washington State Patrol pilot flying overhead, radioed he had two readings of 75 mph on a black sedan traveling southbound on the freeway in a posted 60 mph zone. Upon the direction of the pilot I entered the freeway as the car passed over the overpass I had been parked below. I headed up the on-ramp and set my speed at 70 mph to see if the black sedan would be pulling away from me. As I pulled in behind and in the lane next to this black Lincoln sedan, the pilot radioed, “I now have the car at 80 mph”. I increased my speed to 80 mph as the pilot radioed again, “The car is now doing 90 mph”. I noticed the Lincoln was still pulling away from me so I continued to increase my speed. The pilot radioed, “The black sedan is now at 105 mph”. I have had enough; I sped up to 120 mph to get in behind the Lincoln to end this. The driver noticed my red lights, pulled over and stopped.');

INSERT INTO books (author, title, isbn, image_url, description) VALUES('Hugh Carpenter', 'Hot Vegetables', '9780898159752', 'http://books.google.com/books/content?id=ebI9AAAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api', 'description": Another hit in the authors` "Hot" cookbook series, this book draws on the world`s hottest flavors from Asia, the Mediterranean, the American South, and South America create a uniquely exciting fusion cuisine. Color photos.');

INSERT INTO books (author, title, isbn, image_url, description) VALUES('Richard McGregor', 'The Party', '9780061998089', 'http://books.google.com/books/content?id=TxchbfKHfhsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'description": Few outsiders have any realistic sense of the innards, motives, rivalries, and fears of the Chinese Communist leadership. But we all know much more than before, thanks to Richard McGregor’s illuminating and richly-textured look at the people in charge of China’s political machinery.... Invaluable.” — James Fallows, National Correspondent for The Atlantic The Party is Financial Times reporter Richard McGregor’s eye-opening investigation into China’s Communist Party, and the integral role it has played in the country’s rise as a global superpower and rival to the United States. Many books have examined China’s economic rise, human rights record, turbulent history, and relations with the U.S.; none until now, however, have tackled the issue central to understanding all of these issues: how the ruling communist government works. The Party delves deeply into China’s secretive political machine.');

INSERT INTO books (author, title, isbn, image_url, description) VALUES('Brian R. Little', 'Who Are You, Really?', '9781501119965', 'http://books.google.com/books/content?id=ZCEwDwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'description": Traditionally, scientists have emphasized what they call the first and second natures of personality--genes and culture, respectively. But today the field of personality science has moved well beyond the nature vs. nurture debate. In Who Are You, Really? Dr. Brian Little presents a distinctive view of how personality shapes our lives--and why this matters. Little makes the case for a third nature to the human condition--the pursuit of personal projects, idealistic dreams, and creative ventures that shape both people`s lives and their personalities. Little uncovers what personality science has been discovering about the role of personal projects, revealing how this new concept can help people better understand themselves and shape their lives" -- provided by publisher.');

INSERT INTO books (author, title, isbn, image_url, description) VALUES('Ben Clanton', 'Narwhal', '9781101918265', 'http://books.google.com/books/content?id=6ej4DAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'description": A happy-go-lucky, waffle-loving narwhal and a cynical, no-nonsense jellyfish forge an unlikely friendship and share adventures while exploring the ocean together.');

INSERT INTO books (author, title, isbn, image_url, description) VALUES('Melinda Long', 'How I Became a Pirate', '9780152018481', 'http://books.google.com/books/content?id=9OdooYJSetgC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api', 'description": Jeremy Jacob joins Braid Beard and his pirate crew and finds out about pirate language, pirate manners, and other aspects of their life.');